name: weather_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.3+8

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  lottie: ^2.3.2
flutter:
  uses-material-design: true
  assets:
     - assets/
flutter_icons:
  ios: true
  android: true
  image_path: "lib/assets/icon.png"